modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="ae2_additions"
version="${file.jarVersion}"
displayName="应用能源扩展"
authors="edebe"
[[dependencies.ae2_additions]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ae2_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ae2_additions]]
    modId="appliedenergistics2"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
